import e from "express";
import { login, logout, register } from "../controllers/authController.js";
const Router = e.Router();
Router.post("/login", login);
Router.post("/logout", logout);
Router.post("/register", register);
// Router.get("/me");
// Router.put("/me");
// Router.delete("/me");
export default Router;
